Now the panel script can manage all screens!!

diff --git a/herbstluftwm/helpers.d/panel b/herbstluftwm/helpers.d/panel
--- a/herbstluftwm/helpers.d/panel
+++ b/herbstluftwm/helpers.d/panel
@@ -6,36 +6,44 @@ CFGDIR="${XDG_CONFIG_HOME:-$HOME/.config}/herbstluftwm"
 ## Also load color config and current theme opts:
 . "${CFGDIR}/themes.d/current/colors.conf"
 . "${CFGDIR}/themes.d/current/opts.conf"
+fifo_events="${PANEL_FIFO}"
 
 hc() { "${herbstclient_command[@]:-herbstclient}" "$@" ;}
 get_volume() { "${HLPDIR}/volume" get ;}
 
-monitor="${1:-0}"
-geometry=$(herbstclient monitor_rect "$monitor" | $AWK "{printf \"%sx%s+%s+%s\"values,\$3,\"${PANELHEIGHT}\",\$1,\$2;}")
-[[ -z "$geometry" ]] && echo "Invalid monitor $monitor" && exit 1
-
-bgcolor="${IN_FRAMEBR}"
-selbg="${AC_WINBR}"
-selfg="${SE_TEXT}"
-
-fifo_events="${PANEL_FIFO}.${monitor}"
-if [[ "$2" = "debug" ]]; then
+## Get launch options:
+while getopts "dm:" opt; do
+    case $opt in
+        m) monitors+=("$OPTARG");;
+        d) debug=on;;
+    esac
+done
+[[ -z "$monitors" ]] && echo "No monitors specified." && exit 1
+for monitor in "${monitors[@]}"; do
+    # geometry["$monitor"]=$(herbstclient monitor_rect "$monitor" | $AWK "{printf \"%sx%s+%s+%s\"values,\$3,\"${PANELHEIGHT}\",\$1,\$2;}")
+    # [[ -z "$geometry" ]] && echo "Invalid monitor $monitor" && exit 1
+    # Pad the screen to panel height:
+    hc pad "$monitor" "$PANELHEIGHT"
+done
+if [[ "$debug" = "on" ]]; then
     [[ -e "$fifo_events" ]] && rm "$fifo_events"
     mkfifo -m600 "$fifo_events"
 else
     [[ -p "$fifo_events" ]] || notify-send -u critical "Panel error!" "No FIFO found!"
 fi
 
-# Pad the screen to panel height:
-hc pad "$monitor" "$PANELHEIGHT"
+
+bgcolor="${IN_FRAMEBR}"
+selbg="${AC_WINBR}"
+selfg="${SE_TEXT}"
 
 ## Read the taglist and create the tag widget contents:
 gentagline () {
     # Switch the font to glyphs:
-    tagline="%{T2}"
+    tagline["${1}"]="%{T2}"
     # Read the tag list:
     # IFS=$'\t' read -ra tags <<< "$(hc tag_status $monitor)"
-    tags=( $(hc tag_status $monitor) )
+    tags=( $(hc tag_status "${1}") )
     ## Tag statuses:
     #  '#' -- Tag is active and focused on current monitor;
     #  '+' -- Tag is active on current monitor,
@@ -50,10 +58,10 @@ gentagline () {
             '!' ) tagcolor="%{B${UR_WINBR}}%{F$selfg}";;
             *   ) tagcolor="%{B-}%{F${IN_TEXT}}";;
         esac
-        tagline+="${tagcolor}%{A:herbstclient chain .-. focus_monitor \"${monitor}\" .-. use \"${tags[i]:1}\":} ${tag_icons[i]} %{A}"
+        tagline["${1}"]+="${tagcolor}%{A:herbstclient chain .-. focus_monitor \"${1}\" .-. use \"${tags[i]:1}\":} ${tag_icons[i]} %{A}"
     done
     #  Switch font back to text:
-    tagline+="%{T1}"
+    tagline["${1}"]+="%{T1}"
 }
 
 parsecmd () {
@@ -62,8 +70,11 @@ parsecmd () {
     #  (quit_panel/togglehidepanel/reload) are also handled here.
     cmd="$1"
     case "${cmd[0]}" in
-        tag*       ) gentagline;;
+        tag*       ) for monitor in "${monitors[@]}"; do
+                         gentagline "$monitor"
+                     done;;
         conky      ) conky="${cmd[1]}";;
+        battery    ) battery="${cmd[1]}";;
         quit_panel ) exit;;
         reload     )
             pkill -P $$
@@ -85,7 +96,9 @@ herbstclient --idle | $AWK '$0 != l { print ; l=$0 ; fflush(); }' > "$fifo_event
 fi
 
 ## Pre-fill data:
-gentagline
+for monitor in "${monitors[@]}"; do
+    gentagline "$monitor"
+done
 conky=""
 layout="$(skb -1)"
 windowtitle="Welcome home."
@@ -96,11 +109,15 @@ SEPARATOR="%{B-}%{F$selbg}|%{F-}"
 while IFS=$'\t' read -ra cmd; do
     # Parse the event:
     parsecmd "${cmd}"
-    # Draw tags and window title:
-    printf "%s" "${tagline}${SEPARATOR} ${windowtitle//%{/% {}"
-    # Draw info stuff on the right side of the panel and finish the line:
-    printf "%s\n" "%{r} $layout $SEPARATOR $volume $SEPARATOR $conky "
+    BAR_DATA=""
+    for monitor in "${monitors[@]}"; do
+        # Draw tags and window title:
+        BAR_DATA+="%{S${monitor}}%{l}${tagline[${monitor}]}${SEPARATOR} ${windowtitle//%{/% {}"
+        # Draw info stuff on the right side of the panel and finish the line:
+        BAR_DATA+="%{r} $layout $SEPARATOR $volume $SEPARATOR $battery $SEPARATOR $conky "
+    done
+    printf "%s\n" "${BAR_DATA}"
 done < "$fifo_events" |\
-    lemonbar -g "${geometry}" \
+    lemonbar -g "x${PANELHEIGHT}" -a 20 \
              -f "${TEXTFONT}" -f "${GLYPHFONT}" \
              -B "$bgcolor" -F "${AC_TEXT}"
